"""initial schema

Revision ID: 026bac5491bd
Revises: 
Create Date: 2026-01-21 13:15:51.070738

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "026bac5491bd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complaints",
        sa.Column("complaint_id", sa.UUID(), nullable=False),
        sa.Column("user_sub", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column(
            "step",
            sa.Enum(
                "EVIDENCE",
                "TIMELINE",
                "DOCUMENT",
                "COMPLETE",
                name="complaintstep",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("complaint_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_sub", sa.String(length=36), nullable=False),
        sa.Column("is_legal_representative", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_sub"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("complaints")
    # ### end Alembic commands ###
