"""add task status cancelled

Revision ID: 2dd6a24f6735
Revises: 8c9a80842d31
Create Date: 2026-04-24 21:14:54.559777

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2dd6a24f6735"
down_revision: Union[str, Sequence[str], None] = "8c9a80842d31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
