"""victim durations nullable

Revision ID: 413cf87ca718
Revises: 7dce2f685345
Create Date: 2026-03-08 19:20:52.774236

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "413cf87ca718"
down_revision: Union[str, Sequence[str], None] = "7dce2f685345"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "evidence_victims", "duration_seconds", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "evidence_victims", "duration_seconds", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
