"""add pdf columns in incident_log

Revision ID: 41bdeb05fe47
Revises: a1b2c3d4e5f6
Create Date: 2026-03-13 15:45:42.757800

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41bdeb05fe47"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evidence_incident_log_form_data",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "evidence_incident_log_form_data",
        sa.Column(
            "pdf_created_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="FORM_DATA PDF 최종 생성 시각. 재생성 필요 시 비교용",
        ),
    )
    op.add_column(
        "evidence_incident_log_form_data",
        sa.Column(
            "pdf_s3_key", sa.String(length=512), nullable=True, comment="FORM_DATA PDF S3 키"
        ),
    )
    op.alter_column(
        "timeline_evidences",
        "referenced_manual_evidence_id",
        existing_type=sa.UUID(),
        comment="timeline_referenced_manual_evidences.id (is_original_evidence=False일 때)",
        existing_comment="timeline_manual_evidences.id (is_original_evidence=False일 때)",
        existing_nullable=True,
    )
    op.alter_column(
        "timeline_evidences",
        "is_original_evidence",
        existing_type=sa.BOOLEAN(),
        comment="True: AI 분석 증거(evidence_*), False: 직접 추가(timeline_referenced_manual_evidences)",
        existing_comment="True: AI 분석 증거(evidence_*), False: 수동 추가(timeline_manual_evidences)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "timeline_evidences",
        "is_original_evidence",
        existing_type=sa.BOOLEAN(),
        comment="True: AI 분석 증거(evidence_*), False: 수동 추가(timeline_manual_evidences)",
        existing_comment="True: AI 분석 증거(evidence_*), False: 직접 추가(timeline_referenced_manual_evidences)",
        existing_nullable=False,
    )
    op.alter_column(
        "timeline_evidences",
        "referenced_manual_evidence_id",
        existing_type=sa.UUID(),
        comment="timeline_manual_evidences.id (is_original_evidence=False일 때)",
        existing_comment="timeline_referenced_manual_evidences.id (is_original_evidence=False일 때)",
        existing_nullable=True,
    )
    op.drop_column("evidence_incident_log_form_data", "pdf_s3_key")
    op.drop_column("evidence_incident_log_form_data", "pdf_created_at")
    op.drop_column("evidence_incident_log_form_data", "updated_at")
    # ### end Alembic commands ###
