"""expand manual evidence

Revision ID: 464b81be791c
Revises: 678b803de8da
Create Date: 2026-03-11 13:08:42.292317

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "464b81be791c"
down_revision: Union[str, Sequence[str], None] = "678b803de8da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timeline_manual_evidences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("complaint_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.String(length=20),
            nullable=False,
            comment="file_type: IMAGE, AUDIO, VIDEO, DOCUMENT, ETC (content_type에서 파생, evidence_type 없음)",
        ),
        sa.Column(
            "duration_seconds",
            sa.Integer(),
            nullable=True,
            comment="영상/음성 길이(초). 이미지/문서는 NULL",
        ),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("s3_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["complaint_id"], ["complaints.complaint_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "timeline_evidences",
        sa.Column(
            "timeline_evidence_id",
            sa.UUID(),
            nullable=False,
            comment="timeline JSON 내 증거 그룹 id",
        ),
    )
    op.add_column(
        "timeline_evidences",
        sa.Column(
            "manual_evidence_id",
            sa.UUID(),
            nullable=True,
            comment="timeline_manual_evidences.id (is_original_evidence=False일 때)",
        ),
    )
    op.add_column(
        "timeline_evidences",
        sa.Column(
            "is_original_evidence",
            sa.Boolean(),
            nullable=False,
            comment="True: AI 분석 증거(evidence_*), False: 수동 추가(timeline_manual_evidences)",
        ),
    )
    op.add_column(
        "timeline_evidences",
        sa.Column(
            "evidence_type",
            sa.String(length=20),
            nullable=True,
            comment="MESSAGE, VICTIM, VOICE, REPORT_RECORD, INCIDENT_LOG (is_original_evidence=True일 때만)",
        ),
    )
    op.add_column(
        "timeline_evidences",
        sa.Column(
            "file_type",
            sa.String(length=20),
            nullable=False,
            comment="IMAGE, AUDIO, VIDEO, DOCUMENT, ETC (항상 존재)",
        ),
    )
    op.alter_column(
        "timeline_evidences",
        "evidence_id",
        existing_type=sa.UUID(),
        nullable=True,
        comment="evidence_* 테이블 id (is_original_evidence=True일 때)",
        existing_comment="timeline JSON 내 증거 id",
    )
    op.create_foreign_key(
        None,
        "timeline_evidences",
        "timeline_manual_evidences",
        ["manual_evidence_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("timeline_evidences", "type")
    op.drop_column("timeline_evidences", "original_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timeline_evidences",
        sa.Column(
            "original_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
            comment="evidence_victims, evidence_messages 등 실제 증거 테이블의 id",
        ),
    )
    op.add_column(
        "timeline_evidences",
        sa.Column(
            "type",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
            comment="MESSAGE, VICTIM, VOICE, REPORT_RECORD, INCIDENT_LOG",
        ),
    )
    op.drop_constraint(None, "timeline_evidences", type_="foreignkey")
    op.alter_column(
        "timeline_evidences",
        "evidence_id",
        existing_type=sa.UUID(),
        nullable=False,
        comment="timeline JSON 내 증거 id",
        existing_comment="evidence_* 테이블 id (is_original_evidence=True일 때)",
    )
    op.drop_column("timeline_evidences", "file_type")
    op.drop_column("timeline_evidences", "evidence_type")
    op.drop_column("timeline_evidences", "is_original_evidence")
    op.drop_column("timeline_evidences", "manual_evidence_id")
    op.drop_column("timeline_evidences", "timeline_evidence_id")
    op.drop_table("timeline_manual_evidences")
    # ### end Alembic commands ###
