"""remove column complaints.name

Revision ID: 4cdbdb41ce32
Revises: 85a3c9b5d198
Create Date: 2026-01-21 15:53:13.992182

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cdbdb41ce32"
down_revision: Union[str, Sequence[str], None] = "85a3c9b5d198"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("complaints", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complaints", sa.Column("name", sa.VARCHAR(length=20), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
