"""add columns in caching

Revision ID: 52dc517de34f
Revises: b8c9d0e1f2a3
Create Date: 2026-04-17 13:57:23.657147

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52dc517de34f"
down_revision: Union[str, Sequence[str], None] = "b8c9d0e1f2a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documents")
    op.add_column("cachings", sa.Column("complaint_id", sa.UUID(), nullable=False))
    op.add_column(
        "cachings",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None, "cachings", "complaints", ["complaint_id"], ["complaint_id"], ondelete="CASCADE"
    )
    op.alter_column(
        "evidence_incident_log_files",
        "file_created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="원본 파일 생성 시각",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence_messages",
        "file_created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="원본 파일 생성 시각",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence_report_records",
        "file_created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="원본 파일 생성 시각",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence_victims",
        "file_created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="원본 파일 생성 시각",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence_voices",
        "file_created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="원본 파일 생성 시각",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "evidence_voices",
        "file_created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="원본 파일 생성 시각",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence_victims",
        "file_created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="원본 파일 생성 시각",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence_report_records",
        "file_created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="원본 파일 생성 시각",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence_messages",
        "file_created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="원본 파일 생성 시각",
        existing_nullable=False,
    )
    op.alter_column(
        "evidence_incident_log_files",
        "file_created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="원본 파일 생성 시각",
        existing_nullable=False,
    )
    op.drop_constraint(None, "cachings", type_="foreignkey")
    op.drop_column("cachings", "created_at")
    op.drop_column("cachings", "complaint_id")
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("complaint_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "complaint_form_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "statement_form_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "need_complaint_pdf_regeneration",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "need_statement_pdf_regeneration",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.complaint_id"],
            name=op.f("documents_complaint_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("documents_pkey")),
        sa.UniqueConstraint(
            "complaint_id",
            name=op.f("documents_complaint_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
