"""timeline

Revision ID: 678b803de8da
Revises: c885bdac6236
Create Date: 2026-03-11 00:35:25.024046

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "678b803de8da"
down_revision: Union[str, Sequence[str], None] = "c885bdac6236"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timelines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("complaint_id", sa.UUID(), nullable=False),
        sa.Column("timeline_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["complaint_id"], ["complaints.complaint_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("complaint_id"),
    )
    op.create_table(
        "timeline_evidences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timeline_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False, comment="timeline JSON 내 증거 id"),
        sa.Column("index", sa.Integer(), nullable=False, comment="원본 순서 1, 2, 3, ..."),
        sa.Column(
            "original_id",
            sa.UUID(),
            nullable=False,
            comment="evidence_victims, evidence_messages 등 실제 증거 테이블의 id",
        ),
        sa.Column(
            "type",
            sa.String(length=20),
            nullable=False,
            comment="MESSAGE, VICTIM, VOICE, REPORT_RECORD, INCIDENT_LOG",
        ),
        sa.ForeignKeyConstraint(["timeline_id"], ["timelines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timeline_evidences")
    op.drop_table("timelines")
    # ### end Alembic commands ###
