"""rename column prefix referenced

Revision ID: 6f57a2aeb16d
Revises: 464b81be791c
Create Date: 2026-03-12 17:54:44.208919

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f57a2aeb16d"
down_revision: Union[str, Sequence[str], None] = "464b81be791c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timeline_evidences",
        sa.Column(
            "referenced_evidence_id",
            sa.UUID(),
            nullable=True,
            comment="evidence_* 테이블 id (is_original_evidence=True일 때)",
        ),
    )
    op.add_column(
        "timeline_evidences",
        sa.Column(
            "referenced_manual_evidence_id",
            sa.UUID(),
            nullable=True,
            comment="timeline_manual_evidences.id (is_original_evidence=False일 때)",
        ),
    )
    op.drop_constraint(
        op.f("timeline_evidences_manual_evidence_id_fkey"), "timeline_evidences", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "timeline_evidences",
        "timeline_manual_evidences",
        ["referenced_manual_evidence_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("timeline_evidences", "evidence_id")
    op.drop_column("timeline_evidences", "manual_evidence_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timeline_evidences",
        sa.Column(
            "manual_evidence_id",
            sa.UUID(),
            autoincrement=False,
            nullable=True,
            comment="timeline_manual_evidences.id (is_original_evidence=False일 때)",
        ),
    )
    op.add_column(
        "timeline_evidences",
        sa.Column(
            "evidence_id",
            sa.UUID(),
            autoincrement=False,
            nullable=True,
            comment="evidence_* 테이블 id (is_original_evidence=True일 때)",
        ),
    )
    op.drop_constraint(None, "timeline_evidences", type_="foreignkey")
    op.create_foreign_key(
        op.f("timeline_evidences_manual_evidence_id_fkey"),
        "timeline_evidences",
        "timeline_manual_evidences",
        ["manual_evidence_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("timeline_evidences", "referenced_manual_evidence_id")
    op.drop_column("timeline_evidences", "referenced_evidence_id")
    # ### end Alembic commands ###
