"""add name, updated_at in complaints

Revision ID: 7c425f55d27d
Revises: b2f6c63662c8
Create Date: 2026-02-04 14:00:43.623182

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c425f55d27d"
down_revision: Union[str, Sequence[str], None] = "b2f6c63662c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default로 기존 행에도 '고소장 제목' 적용, 이후 INSERT 시에도 기본값 사용
    op.add_column(
        "complaints",
        sa.Column(
            "name", sa.String(length=50), nullable=False, server_default=sa.text("'고소장 제목'")
        ),
    )
    op.add_column(
        "complaints",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("complaints", "updated_at")
    op.drop_column("complaints", "name")
    # ### end Alembic commands ###
