"""name change trackings to victims

Revision ID: 7dce2f685345
Revises: f2ca0f295cbe
Create Date: 2026-03-08 18:24:29.418246

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7dce2f685345"
down_revision: Union[str, Sequence[str], None] = "f2ca0f295cbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_victims",
        sa.Column("victim_id", sa.UUID(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("complaint_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("s3_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["complaint_id"], ["complaints.complaint_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("victim_id"),
    )
    op.drop_table("evidence_trackings")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_trackings",
        sa.Column("tracking_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("duration_seconds", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("complaint_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("filename", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("s3_key", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column("content_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("size_bytes", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.complaint_id"],
            name=op.f("evidence_trackings_complaint_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tracking_id", name=op.f("evidence_trackings_pkey")),
    )
    op.drop_table("evidence_victims")
    # ### end Alembic commands ###
