"""add fk complaints.user_sub

Revision ID: 85a3c9b5d198
Revises: 026bac5491bd
Create Date: 2026-01-21 15:35:05.942108

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85a3c9b5d198"
down_revision: Union[str, Sequence[str], None] = "026bac5491bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "complaints", "users", ["user_sub"], ["user_sub"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "complaints", type_="foreignkey")
    # ### end Alembic commands ###
