"""add dropped documents

Revision ID: 8c9a80842d31
Revises: 52dc517de34f
Create Date: 2026-04-17 18:52:11.223851

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c9a80842d31"
down_revision: Union[str, Sequence[str], None] = "52dc517de34f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("complaint_id", sa.UUID(), nullable=False),
        sa.Column("complaint_form_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("statement_form_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "need_complaint_pdf_regeneration",
            sa.Boolean(),
            nullable=False,
            comment="고소장 PDF 재생성 필요 여부",
        ),
        sa.Column(
            "need_statement_pdf_regeneration",
            sa.Boolean(),
            nullable=False,
            comment="진술서 PDF 재생성 필요 여부",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["complaint_id"], ["complaints.complaint_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("complaint_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documents")
    # ### end Alembic commands ###
