"""need_timeline_regeneration flag to false

Revision ID: 99dd649d0076
Revises: 7618089fe8d1
Create Date: 2026-03-25 14:07:33.526010

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "99dd649d0076"
down_revision: Union[str, Sequence[str], None] = "7618089fe8d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
