"""evidence_message model

Revision ID: a0faa163acee
Revises: 7c425f55d27d
Create Date: 2026-02-04 15:10:22.312542

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a0faa163acee"
down_revision: Union[str, Sequence[str], None] = "7c425f55d27d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
