"""voice durations nullable

Revision ID: a2a85f2315bb
Revises: 413cf87ca718
Create Date: 2026-03-08 19:26:25.495851

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2a85f2315bb"
down_revision: Union[str, Sequence[str], None] = "413cf87ca718"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "evidence_voices", "duration_seconds", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "evidence_voices", "duration_seconds", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
