"""add retry_count to task

Revision ID: bc2bdec77496
Revises: d824d6c7ceb1
Create Date: 2026-03-19 22:19:58.900756

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc2bdec77496"
down_revision: Union[str, Sequence[str], None] = "d824d6c7ceb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "tasks",
        sa.Column("retry_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "retry_count")
    # ### end Alembic commands ###
