"""remove witness, risk columns

Revision ID: c885bdac6236
Revises: cb5b0e7588a3
Create Date: 2026-03-10 17:44:28.645122

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c885bdac6236"
down_revision: Union[str, Sequence[str], None] = "cb5b0e7588a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evidence_incident_log_form_data", "perceived_risk")
    op.drop_column("evidence_incident_log_form_data", "witness")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evidence_incident_log_form_data",
        sa.Column("witness", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "evidence_incident_log_form_data",
        sa.Column("perceived_risk", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
