"""add incident log attachment

Revision ID: cb5b0e7588a3
Revises: a2a85f2315bb
Create Date: 2026-03-10 17:32:28.373470

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb5b0e7588a3"
down_revision: Union[str, Sequence[str], None] = "a2a85f2315bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident_log_form_data_attachments",
        sa.Column("attachment_id", sa.UUID(), nullable=False),
        sa.Column("incident_log_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("s3_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_log_id"], ["evidence_incident_logs.incident_log_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("attachment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("incident_log_form_data_attachments")
    # ### end Alembic commands ###
