"""incident-log table

Revision ID: f2ca0f295cbe
Revises: 54b20171ed3f
Create Date: 2026-02-11 01:42:47.478982

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2ca0f295cbe"
down_revision: Union[str, Sequence[str], None] = "54b20171ed3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_incident_logs",
        sa.Column("incident_log_id", sa.UUID(), nullable=False),
        sa.Column("complaint_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "FILE", "FORM_DATA", name="evidenceincidentlogtype", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["complaint_id"], ["complaints.complaint_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("incident_log_id"),
    )
    op.create_table(
        "evidence_incident_log_files",
        sa.Column("incident_log_id", sa.UUID(), nullable=False),
        sa.Column("s3_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_log_id"], ["evidence_incident_logs.incident_log_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("incident_log_id"),
    )
    op.create_table(
        "evidence_incident_log_form_data",
        sa.Column("incident_log_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.Column("location", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("witness", sa.Text(), nullable=True),
        sa.Column("perceived_risk", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["incident_log_id"], ["evidence_incident_logs.incident_log_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("incident_log_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evidence_incident_log_form_data")
    op.drop_table("evidence_incident_log_files")
    op.drop_table("evidence_incident_logs")
    # ### end Alembic commands ###
