name: DB Migrate

on:
  push:
    branches: [dev]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      # push to dev → dev, workflow_dispatch(Use workflow from) main → prod, dev → dev
      ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ 'ap-northeast-2' }}

      - name: Alembic upgrade
        env:
          DATABASE_URL: ${{ env.ENV == 'prod' && secrets.PROD_DATABASE_URL || secrets.DEV_DATABASE_URL }}
        run: poetry run alembic upgrade head
